### ISSUE TITLE
Async getter support

### ISSUE THREAD

**Issue by BerciTheBeast** [rawmodel/framework#81]
I propose the addition of having optional async getters.

For example, the following code would be possible and would work:
```
@prop(...)
public image: string;

@prop({
...
    getter() {
        return getImageUrl(this.image); // call to async function that generates link on the fly
    }
})
```

This would likely also impact serialization.

**Comment by xpepermint** [comment]
Thanks for the proposal @BerciTheBeast. I'm afraid this won't work. Getters and setters can not be `async` because they are "a replacement" for variable default getter and setter.

```ts
var user;
user = 'foo'; // valid
await user = "foo"; // invalid
```

It's always good practice to have deterministic objects where you also explain what's happening. For example:

```ts
model.firstName // a value is present, ok
await model.getRemoveImage() // async process where value is not yet present, ok
```

What I usually do in your case is this:

```ts
const user = new User(); // model instance
await user.loadRemoveImage(); // get remove image and populate the user.image property
user.serialize(); // now I have all the data
```

I hope this helps.
